spring:
  application:
    name: notify
  kafka:
    #bootstrap-servers: localhost:9092 #para uso local
    bootstrap-servers: kafka:9092 #para uso com docker
    consumer:
      group-id: notify_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 9090
